# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: f6089e0681fd8fd43124f957d20b231dd356dcc20fa41c99784f103c3806ba5f694028b4f76c9f621be493cc2308d0ae11610af7d8ce2ca67ad229f1add5c98b

test:
  secret_key_base: 3eeee63e7e4cd9a12baf78b8619b6772054f7d039e94eb90bf258c9bfdc755d2cc62dd181a00b7fc3d797416a5828f99d2689c2255b6c48f1b2000fb496a58a1

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
